name: CI
on: [pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          ~/go/bin/
        key: gocache
    - name: CI - Verifications and Tests
      run: |
        make toolchain
        echo "/usr/local/kubebuilder/bin" >> $GITHUB_PATH
        make ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage.html
